script: 'ci/travis.rb'
before_install:
  - gem install bundler
rvm:
  - 1.9.3
  - 2.0.0
matrix:
  allow_failures:
    - rvm: 2.1
  fast_finish: true
env:
  - "GEM=railties"
  - "GEM=ap,am,amo,ares,as"
  - "GEM=ar:mysql2"
bundler_args: --path vendor/bundle
