language: ruby
rvm:
  - "1.9.3"
services:
  - memcached
before_install:
  - mysql -uroot -e 'grant all on *.* to rails@localhost;'
  - mysql -urails -e 'create database activerecord_unittest;'
  - mysql -urails -e 'create database activerecord_unittest2;'
branches:
  only:
    - 2-3-square
